name: Action CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: windows-latest
            platform: windows x64
            build-command: ./gradlew createReleaseDistributable
            artifact-path: composeApp/build/compose/binaries/main-release/app
            artifact-name: project-windows-x64

          - os: ubuntu-latest
            platform: linux x64
            platformEx: android aarch64
            build-command: ./gradlew createReleaseDistributable
            build-commandEx: ./gradlew assembleDebug && ./gradlew assembleRelease
            artifact-path: composeApp/build/compose/binaries/main-release/
            artifact-pathEx: composeApp/build/outputs/apk/release
            artifact-name: project-linux-x64
            artifact-nameEx: project-android-aarch64

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./gradlew

      - name: Decode Android signing key
        if: matrix.platformEx == 'android aarch64'
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks

      - name: Build ${{ matrix.platform }} platform
        run: ${{ matrix.build-command }}

      - name: Build ${{ matrix.platformEx }} platform
        if: matrix.platformEx == 'android aarch64'
        run: ${{ matrix.build-commandEx }}
        env:
          KEYSTORE_PATH: "./keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          compression-level: 9

      - name: Upload ${{ matrix.platformEx }} artifact
        if: matrix.platformEx == 'android aarch64'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-nameEx }}
          path: ${{ matrix.artifact-pathEx }}
          compression-level: 9
